apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  serviceAccountName: jenkins-agent
  securityContext:
    fsGroup: 1000   # gives write access to shared volumes
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ["$(JENKINS_SECRET)", "$(JENKINS_NAME)"]
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent/workspace
      tty: true
    - name: maven
      image: maven:3.9.9-eclipse-temurin-17
      command:
        - cat
      tty: true
      volumeMounts:
        - name: maven-cache
          mountPath: /root/.m2
        - name: workspace
          mountPath: /home/jenkins/agent/workspace
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
        - name: workspace
          mountPath: /home/jenkins/agent/workspace
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - "/bin/sh"
        - "-c"
        - "sleep 99d"
      tty: true
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
        - name: workspace
          mountPath: /home/jenkins/agent/workspace
    - name: trivy
      image: aquasec/trivy:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent/workspace
    - name: snyk
      image: snyk/snyk:maven-rc
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: workspace
          mountPath: /home/jenkins/agent/workspace
  volumes:
    - name: maven-cache
      emptyDir: {}
    - name: workspace
      emptyDir: {}   # Shared workspace for all containers
    - name: docker-config
      secret:
        secretName: docker-config  # This is your Docker registry credentials secret
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: kubeconfig
      secret:
        secretName: kubeconfig  # ← your kubeconfig secret
